### ISSUE TITLE
Colour picker

### ISSUE THREAD

**Issue by seaj1one** [builderius/builderius#10]
It would be nice having a colour picker where you can create a colour palette similar to the one on Bricks builder. It allows you to have multiple colour palettes that would accommodate CCS frameworks. Each colour could be stored as a variable and easily used throughout the website.

Check out the link - https://bricksbuilder.io/design/

**Comment by seaj1one** [comment]
![image](https://user-images.githubusercontent.com/72103864/188495290-ae36499c-e805-46b7-a134-b6776bef0e52.png)

Here's a snip I took from your tool. I forgot to mention that I can't move the colour picker.

**Comment by seaj1one** [comment]
Here's Brick's colour palette for reference.

![image](https://user-images.githubusercontent.com/72103864/188495676-06deabfb-8207-45eb-a34b-5478bc394089.png)

**Comment by seaj1one** [comment]
You can pick a colour and save it to the colour palette.

**Comment by mrpsiho** [comment]
Thanks! It is a good suggestion!

**Comment by mrpsiho** [comment]
Consider it as done due to changes in upcoming new version.
