### ISSUE TITLE
Can we avoid website design touching the bottom of the viewport.

### ISSUE THREAD

**Issue by seaj1one** [builderius/builderius#106]
If you get to the bottom of the view port, your design is touching the bottom. As an example say you build a hero which is 80vh. You then create a section below. All the element at stuck to the bottom. I can make the screen zoom but would like it if there was some default margin/padding at the bottom so that my elements wouldn't touch the bottom. Only in builderius.

**Comment by mrpsiho** [comment]
@seaj1one  I don't think this is good practice. The idea is that you get 100% of what you see in the builder mode. You could create a temp div and put some height for it and have your spacing bottom.
