### ISSUE TITLE
Can we make the font size a min of 16px for accessibility reasons. 

### ISSUE THREAD

**Issue by seaj1one** [builderius/builderius#108]
Can we make the font size a min of 16px for accessibility reasons?

**Comment by mrpsiho** [comment]
@seaj1one In UI? This to be considered for the new UI.

**Comment by seaj1one** [comment]
@mrpsiho Oh yeah in the UI, that's great. Just in case can relative units be used if possible please.

**Comment by mrpsiho** [comment]
Consider it as irrelevant due to changes in upcoming new version.
