### ISSUE TITLE
Reorganise CSS panel

### ISSUE THREAD

**Issue by seaj1one** [builderius/builderius#11]
Under the CSS setting, it can feel like there's an endless Scholl, more so under the layout. Brick collapses the tabs when you select another tab. Also, bricks use icons where possible and have tool tips. Another suggestion is to use an icon and a modal to display further options. A great space saver and makes it feel a little less cluttered.

**Comment by mrpsiho** [comment]
Thanks!
I would suggest using search functionality. Indeed we have many CSS settings with many choices each, and I simply do not see how to accommodate them under icons. Popovers will not help here as well.

**Comment by seaj1one** [comment]
Hopefully, this will help. Both use an icon with a modal and tool tips.

Take something small like Margins and padding. Say you had both as icons and if you over them, you'll be able to see what they are. Using tooltips, you then hover over the icon and know that it relates to Margin or Padding. You then click on the icon to open a modal with the settings. These are just examples. You can search if you know what you are looking for and if it's available. I Wouldn't say it's urgent, but when you compare it to Bricks, it's quicker to find stuff in Bricks. I would say, though, that you have more settings. 

Anything that would say space in the builder would be a benefit. 

https://recoda.me/

https://bricksbuilder.io/

**Comment by thisbit** [comment]
@seaj1one
this is worked on, however, tooltips and modals are considered bad practice and should be used only when there is no other option. We beleive the option / button itself should be clear in what it represents, or at least easily learnable (like after you click it once, it stays with you what it is). Tooltips can be used for extra info but not crucial info.

We will definitely make the space less overwhelming. And we have pretty clear plans as to how to do this. As we focus on css settings in the new UI design (next in line after the query builder) we will share our progress in the community.

**Comment by mrpsiho** [comment]
Consider it as done due to changes in upcoming new version.
