### ISSUE TITLE
Input a value in gap without the need to select display flex or grid

### ISSUE THREAD

**Issue by seaj1one** [builderius/builderius#111]
When I'm trying to add a css varible of gap I'm having to declare display grid or flex after I've already declared flex or grid on the parent. It'll improve my workflow as I keep forgetting and wonder why the gap is not working.

**Comment by mrpsiho** [comment]
@seaj1one CSS prop `gap` works for flex/grid elements only. Where do you want to use `gap`? In the child element?

**Comment by seaj1one** [comment]
@mrpsiho Yeah the children. I may have got it wrong but I thought child items inherit the flex container. If this is not the case and I have to set child items to display flex before using the gap property then I'm happy for this to be closed.

**Comment by mrpsiho** [comment]
Consider it as irrelevant due to changes in upcoming new version.
