### ISSUE TITLE
The ability to input CCS units/selectors not available in the builder.

### ISSUE THREAD

**Issue by seaj1one** [builderius/builderius#113]
I'd like to be able to input any css units/selectors in the builder. You've got logical units on the way and it'll save me having to go to a code editor to write custom CSS.

**Comment by thisbit** [comment]
- this is a planed enhancement
- however if you use css variables they take any value, functions like clamps etc .. whaetever

**Comment by seaj1one** [comment]
Actually, thinking about it writing custom CSS in the custom css part of any template or component isn't too bad. So I think I'll close this one.
