### ISSUE TITLE
Renaming class names issue

### ISSUE THREAD

**Issue by seaj1one** [builderius/builderius#118]
I had a class name called feature list but decided to change it to feature container. I lost all of my styling because the name changed. I expected the class name to be updated on all elements that it's used. 

I then went to the element and updated the name to feature container and styling returned which is fine. If you had a repeat the same task and update the name on several pages. Depending on how many pages you may miss a page or element. 

If you created a class name globally and date the class name, can this be updated globally. My suggestion is only for the class name that is applied globally. The same if you updated the class name, per template or module.  It only updates the class name if applied per template or per module.

I suggest it this way just in case I create the same class name globally, per template or module with different styling.

**Comment by thisbit** [comment]
Good suggestion

**Comment by mrpsiho** [comment]
Consider it as irrelevant due to changes in upcoming new version.
