### ISSUE TITLE
Query the current date

### ISSUE THREAD

**Issue by seaj1one** [builderius/builderius#126]
I wasn't able to see an option for select the current date. I'm creating a footer and looking to add Copyright 2023 but I'm looking for the year to update automatically if I can please.

**Comment by thisbit** [comment]
Here it is you just use the date() function from php ;)
```
query {
    curYear: php_function_output(function: "date", arguments: ["Y"])
}
```

**Comment by seaj1one** [comment]
Thanks for this.

**Comment by thisbit** [comment]
You're welcome
