### ISSUE TITLE
Add an option to disable the CSS Settings panel for a free coding area with a pre-processor

### ISSUE THREAD

**Issue by DahmaniAdame** [builderius/builderius#13]
Currently, you provide two options to edit CSS: 

- The CSS Settings: requires knowing where each option is located and manually toggling and ticking options. 
- The Custom CSS modal: requires saving and doesn't support pre-processors like LESS or SCSS. 

Both options do the job, but they are slowing down the process. 

Having a flat CSS area where we can code using nested selectors and see the result immediately without requiring to save will be much leaner and faster. 

This is what plugins like Microthemer or CSS Hero provide. They provide both experiences, one like you are providing and another one with a free-coding area. 

If this is not something you plan to do, would you mind still adding a way to disable the CSS Setting module and build compatibility with at least Microthemer? Its developer is very responsive and will welcome another integration (they already have one with pretty much all major builders)

A native implementation would be much better though, to avoid any overhead induced by using multiple plugins relying extensively on JavaScript and DOM manipulation.

**Comment by DahmaniAdame** [comment]
The implementation should have a Global and Page-specific CSS. That will make it easier to work on both when needed 🙏

**Comment by thisbit** [comment]
@DahmaniAdame & @mrpsiho 
Adding to this.

Currently we have a search implementation that helps finding any css setting in the css ui. I have no ide where settings are other then the most ofetn used, like display property or font size property, yet, using the inbuilt search, I can get to them really fast.

What we are currently working on right now (design is done actually)?
- the code editor
- we are ditching the modal window approach, and replacing it with a full blown panel for the code editor, one click (and shortcut) away at all times 
- editor features: 
-- scoping (template or global)
-- hot reload for CSS (instant preview like with css settings currently)
-- drag to order (arange your js or css files in the prefered enqueue order)

CSS Settings
- this is next in line for redesign
- we plan to provide a batter workflow for this, I myself am experiencing some drawbacks current UI has, and we will be focusing on improoving the UI side of CSS a lot, we want you to use it more then the editor, but sure, editor will be there when you need it

**Comment by mrpsiho** [comment]
In the upcoming new version there will be code mode for CSS. Adding pre processors is not planned.
