### ISSUE TITLE
Rapidly add html elements to the page

### ISSUE THREAD

**Issue by seaj1one** [builderius/builderius#136]
Say I want to build a card and the card consists of the following:

- Div ( card container)
- Wrapper for the image
- Wrapper for the content
- h3
- p tag
- image 
- button.

It'll be nice if you can add all of the elements in one go.

**Comment by mrpsiho** [comment]
It is either a pre built layout you have to use or custom element (previously created). Custom elements functionality exists in current version and will be available in the new one too.
