### ISSUE TITLE
Create a standalone graphql plugin that can connect to any data source.

### ISSUE THREAD

**Issue by seaj1one** [builderius/builderius#137]
I recently read an article shared by Elvis in a facebook group https://www.smashingmagazine.com/2024/04/how-work-graphql-wordpress-2024/.

That lead me to look at https://gatographql.com/ and I was blown away at what it can do. 

I propose to start with the following features:

- Extend smart forms to work with ACF and Meta Box. As the user submits a form using Builderius smart forms, it creates a post in the WordPress database. It could then send an automated email to the admin or end user. 
- Create the ability to import and export data from Wordpress. Maybe start with WooCommerce but extend it to tools like Metabox and ACF. 

I would say start off by offering the new product free to all existing Builderius and Uni-Cpo customers and all future features for life. Why you may ask, it's free advertising and a reward for buying Builderius before 1.0. 

For any new customers could bundle it into the cost as a free addon or charge separately. Either way, factor it in the cost. 

The key is to design it for non devs but don't limit devs. 

For pricing you could charge between $20 - $40 and as you add new features, increase the price.

**Comment by mrpsiho** [comment]
Thanks for the suggestion. Let's focus on Builderius atm ;)
