### ISSUE TITLE
Template settings to add after opening and before closing for <head> and <body>

### ISSUE THREAD

**Issue by DahmaniAdame** [builderius/builderius#14]
It will be useful to have a way to inject content after the opening <head> and <body> tags as well as before the closing </head> and </body> tag. 

This will allow us to use performance improvements, like resource hints, based on dynamic data. 

It's basically reserving 4 Raw HTML elements to output their contents in the above locations.

Here is a concrete example. 

Most pages use a hero section with a hero image. Performance-wise, and since this image is loaded above the fold, preloading it will benefit the page's performance. 

Having a HTML field where we can input `<link rel="preload" as="image" href="[[[singular.queried_post.hero_image_url]]]">` will automate the process while building the template without requiring to use another tool to do that manually. 

That would apply to all [resource hints](https://caniuse.com/?search=resource%20hints).

If you decide to go through with this, please consider: 

1 - Provide an inline condition logic to help only add the specific HTML when the dynamic element is present.
Some like the Mustache logic since it seems that Builderius is using `MustacheJS`: 

```
{{#singular.queried_post.hero_image_url}}
<link rel="preload" as="image" href="{{singular.queried_post.hero_image_url}}">
{{/singular.queried_post.hero_image_url}}
```

2 - Provide a way to loop inline dynamic data. 

Sticking with the Mustache example, something like the following if the data has multiple values: 

```
{{#singular.queried_post.hero_image_url}}
<link rel="preload" as="image" href="{{url}}">
{{/singular.queried_post.hero_image_url}}
```

Assuming that `singular.queried_post.preloadable_images` will be stored as: 

```
{
  "preloadable_images": [
    { "url": "domain.ext/1.jpg" },
    { "url": "domain.ext/2.jpg" },
    { "url": "domain.ext/3.jpg" }
  ]
}
```

**Comment by mrpsiho** [comment]
Good, very good suggestion! Thanks!
What about the footer? What use cases would be there, what do you think?

**Comment by DahmaniAdame** [comment]
> What use cases would be there, what do you think?

Low-priority HTML, like popups' contents, declaring JS variables and adding non-critical JS files come to mind.

**Comment by mrpsiho** [comment]
@DahmaniAdame 
For popup content and declaring JS and any custom JS inside the template I use Raw HTML module and write anything I need inside `<script>` tag.
Then, we have CSS/JS libs manager for adding links to CSS and JS libraries in header or footer.

What we do not have is a possibility to add such custom links as you described into `<head>`. It would be a great addition, I think.

**Comment by den-v** [comment]
@DahmaniAdame we have added "template parts" functionality. This is the first step - now template parts can be injected just in Builderius templates. Second step - template parts on hooks. It will be possible to use core wp hooks (like wp_head or wp_footer) or themes hooks (for example GeneratePress - https://docs.generatepress.com/article/hooks-visual-guide/) to put there our template parts. It should fix the need you described (of course we will add new modules like "Link", "Script", "Style", "Meta"...... for template parts)

**Comment by DahmaniAdame** [comment]
@den-v sounds good. But that would cover only the `head` and `footer`. 

It doesn't cover right after the opening `body` tag and right before the `body` closing tag. 

Does Builderius have hooks located there?

**Comment by den-v** [comment]
@DahmaniAdame 
wp_footer running right before `body` closing tag (it will be possible to set priority for template parts hooks also)
wp_head running right before `head` closing tag
Now builderius does not have any own hooks, but we can add. Please tell what do you want to add right after body opening tag

**Comment by DahmaniAdame** [comment]
@den-v just to comply with trackers that ask for adding their scripts either after the `body` opening tag or just before the `body` closing tag. 
`wp_footer` can indeed be used to place something before the `body` closing tag, but to avoid any order overlap, it's best to just add a hook specifically positioned before the `body` closing tag. 
There is no hook that can be used to add something right __after__ the `body` opening tag.

**Comment by thisbit** [comment]
@DahmaniAdame 
you can use `wp_body_open`  hook for what you ask. [wp dev page](https://developer.wordpress.org/reference/hooks/wp_body_open/)

**Comment by mrpsiho** [comment]
CC @DahmaniAdame @thisbit 
@den-v Maybe we should add `wp_body_open` into the twig template? Thoughts? We do not have to invent our own name. This is the standard hook, but it seems to be relatively new one, so even I did not know about it.

**Comment by mrpsiho** [comment]
> @den-v just to comply with trackers that ask for adding their scripts either after the `body` opening tag or just before the `body` closing tag. `wp_footer` can indeed be used to place something before the `body` closing tag, but to avoid any order overlap, it's best to just add a hook specifically positioned before the `body` closing tag. There is no hook that can be used to add something right **after** the `body` opening tag.

There should be no problem when one uses `wp_footer` to place anything before the body closing tag. It is an action, so unless you remove smth as well, you actually cannot overwrite anything. Moreover, using the one hook is better way to deal with ordering as anything that could be added also goes through the same hook. Just change priority! I would not want to end up with this scenario:

```
our_builderius_hook_before_wp_footer
wp_footer
our_builderius_hook_after_wp_footer
</body>
```
If we add a new hook after `wp_footer`, then I am sure there would be also request to add hook before `wp_footer` etc. It is just not right.

**Comment by thisbit** [comment]
Wherever possible, use standard wp hooks.

**Comment by thisbit** [comment]
@DahmaniAdame & @mrpsiho & @den-v 
Lets get back to this.
We have hook templates now, and we have HTML Code element that can take `<script>` element.

- I can inject at `wp_body_open()` but not at `wp_head` or `wp_footer`
- i cannot use `wp_body_open()` on pages that are completely builderius controled, which makes little sense, due to that `wp_body_open()` happens before any of the buildeirus code appears on the page.

Are there any ways we could inject a code blocks (html code module) into the head, or at the end of the page?

**Comment by mrpsiho** [comment]
So, 
1. we have to add `wp_body_open()` to our regular templates.
2. we still cannot allow using `wp_head` and probably `wp_footer`, right @den-v ?
