### ISSUE TITLE
Create pre-made nav linked to WP menu.

### ISSUE THREAD

**Issue by seaj1one** [builderius/builderius#16]
Could you create a pre-made nav that you can link to any WP menu name that you make in WordPress? You can create your own. As demonstrated in your video, it's something that every website will need.

**Comment by mrpsiho** [comment]
Theoretically - yes, sure. Practically - I do not see a reason for this. This contradicts with the philosophy of the builder. We follow the data agnostic approach, which means interchangeable data sources for any views. Your idea is to create a module with locked-in data source.

**Comment by mrpsiho** [comment]
Yes, like this. Also, the proper way to go is to use ready-made layouts. Made by you or others. There is not many of them at the moment, but it will better latter.
