### ISSUE TITLE
Max width on the paragraph module please.

### ISSUE THREAD

**Issue by seaj1one** [builderius/builderius#17]
Would it be possible to have a max-width on the paragraph input box please. If I copy text within the box, I'll need to scholl to see all of the text. 

![image](https://user-images.githubusercontent.com/72103864/189979746-a1770d5d-eeac-41e8-afab-9ee37abb3231.png)

**Comment by mrpsiho** [comment]
We have released the new version of the builder with Monaco editor and currently we are testing how it works if there is no horizontal scroll in this area. Do you like it better now?

**Comment by seaj1one** [comment]
Defiantly no Scholl, but may have discovered a new small problem. 

The first screenshot shows where I've highlighted the whole of the text. Did you see where extra space is around?

The second screenshot shows where the cursor is quite far to the right. 

![image](https://user-images.githubusercontent.com/72103864/191799433-0d8cb5fc-df98-44b3-911e-7f641a3ecbf8.png)

![image](https://user-images.githubusercontent.com/72103864/191800041-f9fd9207-7b0f-4093-87f7-1af2ac555eab.png)

I'm happy you can log in to my website to test it out. Try to put the cursor in the same place as my second screenshot and see what happens.

**Comment by mrpsiho** [comment]
Could you clarify the problem with the cursor?

As of extra space - please, try select like that , then copy and paste in some google doc and check if those spaces are being transferred as well. If not, then these are not spaces at all.

**Comment by seaj1one** [comment]
I've just done a short loom video.

If I need to make any changes, I can always copy and paste them into another document. It would be nice to do minor edits within the builder. 

https://www.loom.com/share/8f7fb7e4731244e08e036b79f5aa8ee7

**Comment by mrpsiho** [comment]
I understand it now. Thanks for the bug report!

**Comment by mrpsiho** [comment]
@seaj1one 
There is some problem with specific PC/browser or ... hmm.. maybe site setup (?). Let's debug it, ok? I need your feedback!

I use FF v.104, it looks and works great in part that your have reported.
<img width="322" alt="CleanShot 2022-09-23 at 11 07 05@2x" src="https://user-images.githubusercontent.com/2705129/191929206-adf43a4c-3549-4018-960e-479013ba6aaa.png">

Please, let me know what browser do you use?

**Comment by mrpsiho** [comment]
@seaj1one 
I think there something with styles of your site. I saw in your video that colorpicker is completely broken for you. Could you make the screenshot of this too?

**Comment by mrpsiho** [comment]
@seaj1one 
Thanks for the access to your site. I have tried and the results are these:
- the editor works fine for me on your site in FF v.104
- the color picker is completely broken even after deactivating all the plugins
<img width="293" alt="CleanShot 2022-09-23 at 14 23 47@2x" src="https://user-images.githubusercontent.com/2705129/191959984-13d63a5d-6216-43f5-9300-9c136d8a2d26.png">
<img width="268" alt="CleanShot 2022-09-23 at 14 26 03@2x" src="https://user-images.githubusercontent.com/2705129/191959992-8ed06e73-e5dc-41f2-9c55-e952590b78b8.png">
<img width="523" alt="CleanShot 2022-09-23 at 14 23 25@2x" src="https://user-images.githubusercontent.com/2705129/191959994-98d65020-5a97-4542-9807-e4b80e48b595.png">

**Comment by seaj1one** [comment]
> @seaj1one There is some problem with specific PC/browser or ... hmm.. maybe site setup (?). Let's debug it, ok? I need your feedback!
> 
> I use FF v.104, it looks and works great in part that your have reported. <img alt="CleanShot 2022-09-23 at 11 07 05@2x" width="322" src="https://user-images.githubusercontent.com/2705129/191929206-adf43a4c-3549-4018-960e-479013ba6aaa.png">
> 
> Please, let me know what browser do you use?

I currently use Chrome Version 105.0.5195.127

**Comment by mrpsiho** [comment]
This bug was fixed in v.0.9.8.11
