### ISSUE TITLE
As soon as I create a class, can it be saved?

### ISSUE THREAD

**Issue by seaj1one** [builderius/builderius#18]
When I use BEM for creating classes, I like to create the classes and then later set the value. If I don't set the value, the class is not saved. Can it be saved if I create a class? 

It may be helpful for the new class manager you are creating. 

![image](https://user-images.githubusercontent.com/72103864/189980286-a5d16985-3306-4932-8ab7-3fce5431c857.png)

**Comment by mrpsiho** [comment]
The screenshot shows the UI for creating CSS selectors. In particular, you are talking about a class based CSS selector. Creating selector is not equal to creating a class (class name). These are different things.
Specifically to the area of the screenshot - empty CSS selectors will be deleted. This is correct behavior as there no need to keep empty CSS selectors.
