### ISSUE TITLE
Lock classes - prevent the user from updating the wrong class

### ISSUE THREAD

**Issue by seaj1one** [builderius/builderius#22]
When switching between classes, it's easy to update the wrong class. It'll be great to be able to lock the classes to prevent this from happening.

**Comment by mrpsiho** [comment]
Could you clarify? Maybe some example?
Thanks!

**Comment by seaj1one** [comment]
Here's an example 

https://www.youtube.com/watch?v=GC67mIuBBDI&t=1736s

The link should get you to the right time

[28:56] - Global Class Lock (Prevent Accidental Changes)

**Comment by mrpsiho** [comment]
In Builderius you don't switch between classes, but between CSS selectors. You can select only one selector at once, so I just don't see why would you need to lock the chosen selector? Please, show me example of how it is useful in Builderius?

**Comment by seaj1one** [comment]
I just did a loom video. Let me know if you are unable to view the video. 

https://www.loom.com/share/d0af89a956b84080bcc2350610dd80c5?t=167

**Comment by mrpsiho** [comment]
I think classes in those other builders are kind of objects itself, like you can open one module, choose some class ".title" and change color to black, then got to the other module, add this class there, change color to red and the red color will become applied for all elements with class ".title". Am I right?

**Comment by seaj1one** [comment]
You are correct. Having global control is easier for me if a customer decides that he wants to change the title back to black from red. Over time customers may rebrand. Depending on the background colour, I may get into situations where some H1 may need to be white and some black. 

I'm trying to follow BEM "https://css-tricks.com/bem-101" It is beneficial for reusing components on different pages/templates.

**Comment by mrpsiho** [comment]
BEM is a good approach. In this particular situation it is really different, because in Builderius we do not have class manager yet. You screencasted CSS selectors, not "classes as objects like in other builders". And there is really no point to restrict editing CSS selectors. So, I will close this issue.

When we create the manager of classes and implement its usage this or that way, then we could return to such question is the scope of the classes manager. ;)

**Comment by seaj1one** [comment]
That's no problem. Thanks.
