### ISSUE TITLE
Problem with the media library 

### ISSUE THREAD

**Issue by seaj1one** [builderius/builderius#23]
I tried to select an image from the media library and there was a spike with my browser resource. In the screenshot, I used FF 105.0

![image](https://user-images.githubusercontent.com/72103864/191969700-daa77a40-be47-417a-8e63-5426ebf7741b.png)

`https://youtu.be/2JGSQVfrEFw`

**Comment by seaj1one** [comment]
![image](https://user-images.githubusercontent.com/72103864/192039391-0d17996e-b0c3-4de1-a27f-3130837c1f0d.png)

**Comment by seaj1one** [comment]
The media library is fine when copying the WordPress library link.

**Comment by mrpsiho** [comment]
I think it is somehow connected with the type of file you have uploaded. Could you give me more details?

**Comment by seaj1one** [comment]
I used both Chrome and Firefox and deactivated all plugins except for Builderius. 

Try and swap out the background image from my test site if you still have my login details.

**Comment by seaj1one** [comment]
Since the update of Builderius v0.9.8.10 

I'm now able to insert images but the modal is fixed to the top of the page.

![image](https://user-images.githubusercontent.com/72103864/194758060-d085f361-274e-4e10-ac75-ccb99abb2083.png)

**Comment by seaj1one** [comment]
All fine, happy for this issue to be closed.
