### ISSUE TITLE
Best practices but using GraphQL API

### ISSUE THREAD

**Issue by seaj1one** [builderius/builderius#25]
Can you create a video using GraphQL API?

- What tools can we use to query content from WordPress, including any data?
- Best practices per template and global to optimise queries?

Can you put this in a video, please?

**Comment by mrpsiho** [comment]
We have added this video: https://www.youtube.com/watch?v=uOLj05c1rvw
And we have updated the docs: https://docs.builderius.io/docs/settings/datavar/graphql/overview It contains a lot of examples of queries to get different data from DB.
