### ISSUE TITLE
Unable to see all of the GraphQL auto  suggestions before line 6.

### ISSUE THREAD

**Issue by seaj1one** [builderius/builderius#27]
Could you have a look at Graphql autosuggestions? I'm not able to see all of the suggestions before line 6.

![image](https://user-images.githubusercontent.com/72103864/194743997-c6cdc543-78cc-4806-b65c-339f1bed72aa.png)

From line 6, I can see all of the available options. 

![image](https://user-images.githubusercontent.com/72103864/194744163-bda4f2a8-7e37-463b-9923-331f10725724.png)

I cannot see all of the suggestions from lines five and below.

![image](https://user-images.githubusercontent.com/72103864/194744241-9ef4dbb9-f475-4252-bf1d-eef099f47bea.png)

**Comment by thisbit** [comment]
Has this been solved? I cannot reproduce this issue. @seaj1one can you please confirm this issue is gone?

**Comment by seaj1one** [comment]
Sorry for the late reply @thisbit  I wasn't able to login to Builderiues at the time then forgot. It's works find now in firefox.
