### ISSUE TITLE
Relative Styling option

### ISSUE THREAD

**Issue by seaj1one** [builderius/builderius#30]
Cwicly has the option to control the children elements using Relative Styling. In the video, say you hover the button, and the cards disappear to reveal an H2. 

[Cwicly](https://www.youtube.com/watch?v=B-7nQUm8hAk) 

The only thing that I may add is the ability to select any of the following pseudo classes. 

:has 
:where 
:is 
:not

**Comment by mrpsiho** [comment]
This feature works because of using CSS selector combinators. It is a standard CSS feature and it is available in Builderius already.
So, speaking of such possibility - it already is in the builder.
Speaking of a special UI for this - no, it will not be implemented.
