### ISSUE TITLE
Create "Classes manager"

### ISSUE THREAD

**Issue by mrpsiho** [builderius/builderius#31]
It should be possible to easily create classes and assign CSS styles to them. Then it should be easily manageable in the builder mode.

**Comment by seaj1one** [comment]
- Love to see which styles were attached to which element.
- Preview the styles of an element before I commit to the class. I.e. say I have two background colours and the styles are bg-red & bg-blue. I type bg and get results of bg-red & bg-blue and hover over the two classes. I'd like to see a preview before I commit to the class. 
- Copy styles from one element to another.
- Option to prefix classes. i.e. **nav__**menu-item.  (The prefix is in bold and uses BEM).

**Comment by seaj1one** [comment]
Can anyone else thing of any suggestions to add?

**Comment by seaj1one** [comment]
Would it be possible to also do the following:

- Edit and delete classes
- Copy styles from the ID to a class.

**Comment by mrpsiho** [comment]
Consider it as done due to changes in upcoming new version.
