### ISSUE TITLE
Custom layouts cannot be saved

### ISSUE THREAD

**Issue by thisbit** [builderius/builderius#37]
I have noticed a bug, it is the same with dinamyc and static custom made layouts saved inlibrary.
I open a template. I insert. I save. I reload the page and its gone.

If I insert the layot, duplicate it, then save and reload. One stays another does away. I am presuming the one inserted from library goes away and the one duplicated stays. 

New version of plugin free and pro. New version of wp.

**Comment by mrpsiho** [comment]
@thisbit Could you check it again, please? In 0.9.9?

**Comment by thisbit** [comment]
> @thisbit Could you check it again, please? In 0.9.9?

I will

**Comment by thisbit** [comment]
> @thisbit Could you check it again, please? In 0.9.9?

The issue has resolved in the new version, you can close the thread. :+1:
