### ISSUE TITLE
Imprevements/features for CSS component

### ISSUE THREAD

**Issue by thisbit** [builderius/builderius#39]
I am exploring CSS in Builderius and I have several suggestions for improvement.

1. When one writes custom css, like a globally enqueued css, it currently renders as a last css in <head>, this should be optional. I suspect I will want to drop my boilerplate global css styles in there and use the builder to design the more specific stuff. Since this is for sure not the only use case for custom css, I think there should be an option when one creates a "custom css" file, to choose weather it loads "prior to builderius-css" or "after builderius-css". So the file can ovveride builderius css properly, or so builderius can override the custom css properly, depending on the needs.
2. css variable fallback. For instance, this is the proper fallback for font-size var(--some-name, 2rem), this is used when for instance --some-name uses clamp() which is not supported in all browsers. So solution would be either that builderius creates the fallback somehow automatically (probably not feasible) or to add a "fallback" field to variables.

cheers

**Comment by mrpsiho** [comment]
1. The idea is that you have to use module's settings more than anything else. It is the main place one should use to add CSS/styling. Why? Because the settings are structured and later we can do some additional magic with them automatically. For instance - loading critical CSS first etc. Obviously, to do that we have to know which styles are for which modules exactly.
Then - custom CSS should be a fallback for anything that is not possible via settings, like animation atm. Or some specific overrides one cannot live without. So, in this paradigm it is correct behaviour when custom CSS is being loaded after all other CSS.
Additionally, if one would want to use reset styles, their selectors always less specific than anything else. So, yes, then one uses Builder to add more specific styles just because the automatically generated selectors are more specific. They will override without problems.

**Comment by mrpsiho** [comment]
2. Fallbacks are values of settings itself. Let's say one set font-size to 23px and then also adds some var --some-name, then CSS will be automatically generated like this: font-size: `var(--some-name, 23px);` <- fallback is here already. If one does not need fallback - they just has to remove setting's value.

**Comment by seaj1one** [comment]
I belive that no builder can achive every single style that you need without custom CSS. I use https://wpcodebox.com/ if I need use custom CSS. The reason is so that I keep custom CSS in one place.

**Comment by thisbit** [comment]
@mrpsiho 

1. If custom css is fallback, then it should appear before builderius css, regardless of the specificity. Otherwise I see your point.
2. I am not sure I undersand. Lets look at thow scenarios, and tell me what will Builderius generate in terms of fallback?

**Simple Example**

```
--large-type: 34rem;

h1 {
font-size: var(--large-type);
}
```


**A bit more complex example**

```
--my-fluid-type: clamp(1rem, calc(1rem + ((1vw - 0.48rem) * 0.6944)), 1.5rem);

.some-selector {
font-size: var(--my-fluid-type);
}
```

Thanks.

**Comment by mrpsiho** [comment]
> I belive that no builder can achive every single style that you need without custom CSS. I use https://wpcodebox.com/ if I need use custom CSS. The reason is so that I keep custom CSS in one place.

We aimed to fix this - we would want to provide a full list of CSS settings. Currently we certainly lack of animation settings. I have built a site in Builderius without need to use custom CSS except placing custom fonts declarations (this is also are we have to improve).
And I understand why you use wpcodebox for that. But I believe using custom css settings of template/global in Builderius is a better way, as ordering of the code is tested and meant to be just right. Additionally, there is that division of when to load your CSS (this tmpl or globally) that we also prepared for you in advance. It works automatically!

Another question here is how convenient and practical to use custom CSS in general. I would say - it has its benefits when you just write code as you would do this in CSS file without all that visual fuss :) And we are also thinking of improving this: https://github.com/builderius/builderius/discussions/48

**Comment by mrpsiho** [comment]
> 2\. I am not sure I understand. Let's look at two scenarios, and tell me what will Builderius generate in terms of fallback.

I have made screenshots, so it might be easier to understand:
![CleanShot 2022-11-07 at 09 06 51](https://user-images.githubusercontent.com/2705129/200258577-dc6ad0de-82a3-46c5-a422-e1662e9b7ec7.png)
![CleanShot 2022-11-07 at 09 07 28](https://user-images.githubusercontent.com/2705129/200258590-c48761b3-a7b8-4cf2-8742-2b63060a45aa.png)

See? When you use setting and set some value and then you use CSS var - the settings value automatically becomes the fallback.
Even more - when you use more than one CSS var - they become a part of the fallback too.
![CleanShot 2022-11-07 at 09 11 31](https://user-images.githubusercontent.com/2705129/200259007-1b7bf53c-071d-4eae-badb-389e9a337e9f.png)

**Comment by thisbit** [comment]
Ok, this is pretty awesome. However my second example, is important because value of the fallback is not straight forward, so what in that case?

**Comment by mrpsiho** [comment]
@thisbit 
I think this is different topic, actually. What you actually need in this case is a possibility to use CSS functions as CSS settings values. Atm it is not possible. I think there is some tech issues with this approach @den-v ?

Atm you may want to create a new local CSS var (local means - in the module) for your complex clamp() value and use this var as a fallback. It is seen on my third screenshot that CSS vars might also serve as fallbacks.

**Comment by thisbit** [comment]
Yes, thats what I need. Didn't think you could do it via a other var, but that is good enough for now.

**Comment by mrpsiho** [comment]
Consider it as irrelevant due to changes in upcoming new version.
