### ISSUE TITLE
Could you add the ch unit please?

### ISSUE THREAD

**Issue by seaj1one** [builderius/builderius#56]
Could you add the ch unit please?

**Comment by mrpsiho** [comment]
BTW, nice article that explains what is this: https://meyerweb.com/eric/thoughts/2018/06/28/what-is-the-css-ch-unit/

@seaj1one 
To which CSS it should be added? Your suggestion?

**Comment by seaj1one** [comment]
@mrpsiho many thanks.

Would it be possible to add the CH to the following please?

Font
Generic block - I sometimes use a div as a wrapper for my text.
