### ISSUE TITLE
Make Structure panel separate from the main panel

### ISSUE THREAD

**Issue by mrpsiho** [builderius/builderius#6]
The Structure panel should be separated from the main panel as very often it is more convenient to have it opened even when individual module's settings are being edited.

**Comment by thisbit** [comment]
@mrpsiho Interesting idea. Now that you mention it I woul actually recomend that you group modules inserter and structure as for instance one panel (on the left for example) and the module settings, template setings and global setting on another side.

In this way one panel would serve for managing modules in the page, adding new, removing, and moving around, while the other would syncronously change to reveal settings for the curently clicked on module.

This could be an optional builder layout, so users can decide. Or not if that complicates the development.

**Comment by mrpsiho** [comment]
@thisbit 
Yes, probably this way - a new one for adding modules/structure. Another one - the main panel as it is now - for settings.
Also yes - I would try to make it optional, so who wants it - breaks the panel into two. Those who don't - do not break and keep it basically as it is now.
Let's see...

**Comment by thisbit** [comment]
Sound great. I assume most would use separate layout as it is most common in builder tools, however the current one is very good for smaller screens, so for these situations it will be used for sure.

**Comment by mrpsiho** [comment]
Coming in the new version.
