### ISSUE TITLE
Allow for selecting more then one module in the structure (shift + click)

### ISSUE THREAD

**Issue by thisbit** [builderius/builderius#66]
To manage html structre more effectively, we should allow to select more then one module in the structure tree. For instance I create a section, then paste a couple of items (divs), and then decide I need to move items from the section into another section.

- Now i have to do it step by step, module by module
- Select first item in the section, shift select the last one, and drag to another section (gutenberg has this)

Same method should also work for bulk deleting selected modules

**Comment by mrpsiho** [comment]
Consider it as done due to changes in upcoming new version.
