### ISSUE TITLE
Conditions break CSS rendering on the element

### ISSUE THREAD

**Issue by thisbit** [builderius/builderius#69]
1. When I use hook temaplates and create an element, with css styles, they work.
2. Then I apply condition (user not logged in), the condition works, and the module gets rendered, however the exact module which has the condition, looses css
3. All the children keep the css

Workaround

Make the template, style all modules, then wrap all conent with a generic block element without any css applied to it and add condition to it ... now all is good

[custom-search_branch-master_commit-e9dde25b4811a34296df_1_20_2023, 4_15_37 PM.zip](https://github.com/builderius/builderius/files/10467528/custom-search_branch-master_commit-e9dde25b4811a34296df_1_20_2023.4_15_37.PM.zip)

**Comment by den-v** [comment]
fixed at v0.9.9.5
