### ISSUE TITLE
Some CSS settings do now allow for clearing value after the value has been entered

### ISSUE THREAD

**Issue by thisbit** [builderius/builderius#82]
Example: 

1. I set the Background image. 
2. I decide I don't need a background image. 
3. I clear it using the clear button.
4. I hit save button to save the template, I get error related to the backgroundImage field.

The only way to continue the work is to add some value to it, like inherit or something.

**Comment by mrpsiho** [comment]
Need more testing here. I cannot reproduce.

**Comment by mrpsiho** [comment]
Consider it as irrelevant due to changes in upcoming new version.
