### ISSUE TITLE
UX improvements (states)

### ISSUE THREAD

**Issue by thisbit** [builderius/builderius#85]
When I style the button for hover state, it would be good that this state becomes visible in the builder.

**Comment by mrpsiho** [comment]
I don't think it should work like that. CSS selectors are different and act under different circumstances. Some works automatically, like `div > span`, for instance. Or another one: `ul li:nth-first-child(2)` - here the effect will be visible when you have 2 `li` items. If you don't have them, then you should add them. We will not be adding them automatically just for testing. The same goes for `:hover` or `:disabled` etc.
