### ISSUE TITLE
Add dynamic data support for properties values on custom CSS

### ISSUE THREAD

**Issue by DahmaniAdame** [builderius/builderius#9]
Some elements might have dynamic background colors stored as custom fields. 

It will be handy if we can replace a property's values with a dynamic string like `[[[customfields.queried_post.hero_bg_color]]]`. 

It will be difficult to implement on the UI, but it should be easy to allow this at least on the custom CSS level. 

```
<style class="builderius-css">.hero_bg_color {
  background-color: [[[customfields.queried_post.hero_bg_color]]];
}</style>
```

`[[[customfields.queried_post.hero_bg_color]]]` to be replaced by the custom field value when added to the page.

**Comment by den-v** [comment]
@DahmaniAdame it is possible to create css variables based on dynamic data and then use it in css. In order to do this - you should use css variable with type "any-value" like in attached video

https://user-images.githubusercontent.com/8387898/188317738-b4cb47a7-662d-4eba-942b-963ad5541539.mp4

**Comment by den-v** [comment]
And off course it is possible to use this css variable in custom css setting like:
.container {
  background-color: var(--hero-bg-color);
}

**Comment by DahmaniAdame** [comment]
Thanks! Worked as shown in the video 👍
